# Generated by Django 5.2.1 on 2025-07-17 08:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_ddc', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100)),
                ('book_img', models.ImageField(blank=True, default='Books/download.jpg', null=True, upload_to='Books/')),
                ('book_author', models.CharField(max_length=100)),
                ('book_publisher', models.CharField(blank=True, max_length=100)),
                ('book_category', models.CharField(max_length=100)),
                ('book_available', models.BooleanField(default=True)),
                ('book_copies', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('copies_available', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('book_isbn', models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(13)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('reserve_id', models.AutoField(primary_key=True, serialize=False)),
                ('reserved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_status', models.CharField(choices=[('pending', 'Request Pending'), ('not returned', 'Not Returned by Previous User'), ('ready', 'Ready for Pickup'), ('borrowed', 'Borrowed'), ('returned', 'Returned')], default='pending', max_length=12)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_log.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_log.user')),
            ],
            options={
                'db_table': 'library_log_reserve',
            },
        ),
        migrations.CreateModel(
            name='IssueHistory',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_log.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Library_log.user')),
            ],
        ),
    ]
